# Generated by Django 5.2.6 on 2025-12-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="description",
        ),
    ]
