# Generated by Django 5.2.6 on 2025-11-25 10:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('user_key', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('category_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.category')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.temp')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_key', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.DurationField()),
                ('subject_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.subject')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.temp')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='user_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.temp'),
        ),
    ]
