# Generated by Django 5.2.6 on 2025-12-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='record',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
